/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p66.reto4.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.p66.reto4.controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p66.reto4.modelo.vo.Requerimiento_1;
import utp.misiontic2022.c2.p66.reto4.modelo.vo.Requerimiento_2;
import utp.misiontic2022.c2.p66.reto4.modelo.vo.Requerimiento_3;



/**
 *
 * @author eduan
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    
     private DefaultTableModel modeloTabla;
     
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lBarra = new javax.swing.JLabel();
        lTitulo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnProveedores = new javax.swing.JButton();
        BtnBancosVinc = new javax.swing.JButton();
        BtnListaMateriales = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRequerimiento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lBarra1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C&F Construcciones");

        lTitulo.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(51, 153, 255));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lTitulo.setText("C&F");

        lBarra.setBackground(new java.awt.Color(0, 51, 255));
        lBarra.setForeground(new java.awt.Color(51, 153, 255));
        lBarra.setOpaque(true);

        lTitulo2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lTitulo2.setText("Construcciones y Futuro S.A");

        BtnProveedores.setBackground(new java.awt.Color(204, 204, 204));
        BtnProveedores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnProveedores.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduan\\OneDrive\\Escritorio\\MisionTic 2021\\Ciclo 2\\programacion\\unidad 4\\reto4_p66_plantilla\\reto4_p66_esqueleto\\src\\main\\java\\utp\\misiontic2022\\c2\\p66\\img\\proveedor.png")); // NOI18N
        BtnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProveedoresActionPerformed(evt);
            }
        });

        BtnBancosVinc.setBackground(new java.awt.Color(204, 204, 204));
        BtnBancosVinc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnBancosVinc.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduan\\OneDrive\\Escritorio\\MisionTic 2021\\Ciclo 2\\programacion\\unidad 4\\reto4_p66_plantilla\\reto4_p66_esqueleto\\src\\main\\java\\utp\\misiontic2022\\c2\\p66\\img\\bancos.png")); // NOI18N
        BtnBancosVinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBancosVincActionPerformed(evt);
            }
        });

        BtnListaMateriales.setBackground(new java.awt.Color(204, 204, 204));
        BtnListaMateriales.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnListaMateriales.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduan\\OneDrive\\Escritorio\\MisionTic 2021\\Ciclo 2\\programacion\\unidad 4\\reto4_p66_plantilla\\reto4_p66_esqueleto\\src\\main\\java\\utp\\misiontic2022\\c2\\p66\\img\\lista.png")); // NOI18N
        BtnListaMateriales.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnListaMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaMaterialesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("   Proveedores Registrados");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("          Lista de Matriculados");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("          Bancos Vinculados");

        TblRequerimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblRequerimiento);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Elaborado por: Eduan Camilo Mayorga Ruiz");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("MisionTic 2022----------- Ciclo 2");

        lBarra1.setBackground(new java.awt.Color(0, 51, 255));
        lBarra1.setForeground(new java.awt.Color(51, 153, 255));
        lBarra1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lBarra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTitulo2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addComponent(lBarra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(BtnListaMateriales)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnBancosVinc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnListaMateriales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnProveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBancosVinc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lTitulo.getAccessibleContext().setAccessibleName("Titulo");
        BtnListaMateriales.getAccessibleContext().setAccessibleName("ListaMatriculados");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListaMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaMaterialesActionPerformed
            modeloTabla = new DefaultTableModel();
           
            modeloTabla.addColumn("Material");
            modeloTabla.addColumn("Precio Unidad");
            modeloTabla.addColumn("Id del Proyecto");
            TblRequerimiento.setModel(modeloTabla);
            
            requerimiento1();
       
    }//GEN-LAST:event_BtnListaMaterialesActionPerformed

    private void BtnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProveedoresActionPerformed
            modeloTabla = new DefaultTableModel();
           
            modeloTabla.addColumn("Proveedor");
            modeloTabla.addColumn("Cantidad total");
            
            TblRequerimiento.setModel(modeloTabla);
            
            requerimiento2();
    }//GEN-LAST:event_BtnProveedoresActionPerformed

    private void BtnBancosVincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBancosVincActionPerformed
            modeloTabla = new DefaultTableModel();
           
            modeloTabla.addColumn("Banco Vinculado");
            modeloTabla.addColumn("Costo de Lideres");
            
            TblRequerimiento.setModel(modeloTabla);
            
            requerimiento3();
    }//GEN-LAST:event_BtnBancosVincActionPerformed

    /**
     * @param args the command line arguments
     */
   public static final ControladorRequerimientos controlador = new ControladorRequerimientos();

    public  void requerimiento1(){
        try {
            ArrayList<Requerimiento_1> resultados = controlador.consultarRequerimiento1();
                  
           for(Requerimiento_1 re : resultados) {
        	
        	   String datos[] = new String[3];
                   datos[0]= re.getNombreMaterial();
                   datos[1]= "$"+re.getPrecioUnidad();
                   datos[2]= ""+re.getIdProyecto();
                   modeloTabla.addRow(datos);
                   
        	   
           }
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
     public  void requerimiento2(){
        try {
            ArrayList<Requerimiento_2> resultados = controlador.consultarRequerimiento2();
                  
           for(Requerimiento_2 re : resultados) {
        	
        	   String datos[] = new String[2];
                   datos[0]= re.getProveedor();
                   datos[1]= ""+re.getCantidadTotal();
                   modeloTabla.addRow(datos);
                   
        	   
           }
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
    public  void requerimiento3(){
        try {
            ArrayList<Requerimiento_3> resultados = controlador.consultarRequerimiento3();
                  
           for(Requerimiento_3 re : resultados) {
        	
        	   String datos[] = new String[2];
                   datos[0]= re.getBancoVinculado();
                   datos[1]= "$"+re.getCostoLideres();
                   modeloTabla.addRow(datos);
                   
        	   
           }
        } catch (Exception e) {
            System.err.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBancosVinc;
    private javax.swing.JButton BtnListaMateriales;
    private javax.swing.JButton BtnProveedores;
    private javax.swing.JTable TblRequerimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lBarra;
    private javax.swing.JLabel lBarra1;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lTitulo2;
    // End of variables declaration//GEN-END:variables
}
